#!/usr/bin/env python

import consolegui
import sys

if len(sys.argv) == 1 or sys.argv[1] == '--clr':
    gui = consolegui.ConsoleGui()
    gui.main_loop()
else:
    print('GUI interface not implemented yet')
